### ISSUE TITLE
Line should be renamed to Segment

### ISSUE THREAD

**Issue by Piratux** [OneLoneCoder/olcUTIL_Geometry2D#28]
All the functions like overlaps or intersects, assume that line is a segment (finite) as opposed to actual line (infinite).
This may cause confusion.
Therefore I suggest renaming Line class to Segment.

**Comment by OneLoneCoder** [comment]
Whereas I understand the motivation (and dont argue with the accuracy of the sentiment) for this, I'm going to stick with the broader understood definition of a 'line' is the shortest distance between two points, i.e. it's understood a line has a beginning and an end. 

I'd sooner add 'inifinite_line', or better yet, leverage 'ray' somwhow to satisfy this requirement

**Comment by OneLoneCoder** [comment]
Plenty of discussion on discord. TLDR, we will have some sort of infinite_line representation if required.
