### ISSUE TITLE
Consider adding infinite line and its functions

### ISSUE THREAD

**Issue by Piratux** [OneLoneCoder/olcUTIL_Geometry2D#29]
I propose adding new struct called inf_line (or just line, if line gets renamed to segment, see https://github.com/OneLoneCoder/olcUTIL_Geometry2D/issues/28)

Currently functions like overlaps, intersects, etc. are implemented where line is treated as finite segment, but it would be great if there was a set of these functions where line is infinite as well.

**Comment by OneLoneCoder** [comment]
As discussed in #28 'inf_line' or usage of 'ray' is preferred
