### ISSUE TITLE
Intersects ray vs circle should return 2 points in some cases

### ISSUE THREAD

**Issue by Piratux** [OneLoneCoder/olcUTIL_Geometry2D#35]
As the title says, there doesn't seem to be a case where 2 points are returned.
I assume ray vs circle treats ray as infinite line.

**Comment by OneLoneCoder** [comment]
yeah good spot, it should return all positive intersections. Its an infinite line in one direction yeah (lol)

**Comment by OneLoneCoder** [comment]
had a change of heart on this. I think first collision should be default behaviour of ray intersection. Though Im happy to have a variant of the function that returns all intersections. We'll need it for all shapes though. Either that or the intersections need to be sorted to ensure they are returned to the user in order.

**Comment by OneLoneCoder** [comment]
Resolved - vector of ordered points is returned
