### ISSUE TITLE
Rect::side: Not all control paths return a value.

### ISSUE THREAD

**Issue by cugone** [OneLoneCoder/olcUTIL_Geometry2D#36]
`'olc::utils::geom2d::rect<float>::side': not all control paths return a value`

```cpp
// Get a line from an indexed side, starting top, going clockwise
inline line<T> side(const size_t i) const
{
    if ((i & 0b11) == 0) return top();
    if ((i & 0b11) == 1) return right();
    if ((i & 0b11) == 2) return bottom();
    if ((i & 0b11) == 3) return left();
}
```

What should this do if someone passes in a value outside the range `[0,3]`?

- Throw?
- Return an "empty" line equivalent to `pos` (a line where the start and end are the same)?

A better solution should be to pass a `enum class` argument:

```cpp
enum class Side {
    Top
   ,Right
   ,Bottom
   ,Left
};

// Get a line from an indexed side, starting top, going clockwise
inline line<T> side(Side side) const
{
    switch(side) {
        case Top: return top();
        case Right: return right();
        case Bottom: return bottom();
        case Left: return left();
        default: /* DO NOTHING */ break; //Just to appease some over-zealous compilers.
    }
}
```

This eliminates out-of-range values and forces the user to pass in valid values.

**Comment by OneLoneCoder** [comment]
The issue here is the warning is a false positive. The code clearly returns via all control paths, just the compiler isn't smart enough to figure it out.

What value would you pass in that would be out of range?

**Comment by OneLoneCoder** [comment]
I restructured the condition to allow the compiler a chance at not being dumb. Closed.
