### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by jaxfrank** [OneLoneCoder/olcUTIL_Geometry2D#48]
Currently the repo does not contain a LICENSE file. Can a dedicated license file be added to the repo so it cannot be missed?

**Comment by DaveAxiom** [comment]
I found a BSD type license inside of the header file. It'd be nice if the repository page listed such an attribute.

**Comment by TechnicJelle** [comment]
Javid usually uses the OLC-3 licence, which is his own, custom one.
You can see it as a file here, on the PGE: https://github.com/OneLoneCoder/olcPixelGameEngine/blob/master/LICENCE.md
